# Generated by Django 6.0.2 on 2026-02-08 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='name_ar',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='name_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='name_tr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='description_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='description_tr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='title_ar',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='title_tr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='companyfeature',
            name='description_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyfeature',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyfeature',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyfeature',
            name='description_tr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyfeature',
            name='title_ar',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='companyfeature',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='companyfeature',
            name='title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='companyfeature',
            name='title_tr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='description_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='description_tr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='history_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='history_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='history_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='history_tr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='mission_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='mission_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='mission_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='mission_tr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='subtitle_ar',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='subtitle_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='subtitle_ru',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='subtitle_tr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='title_ar',
            field=models.CharField(default='About VAAM', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='title_en',
            field=models.CharField(default='About VAAM', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='title_ru',
            field=models.CharField(default='About VAAM', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='title_tr',
            field=models.CharField(default='About VAAM', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='values_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='values_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='values_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='values_tr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='vision_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='vision_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='vision_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='vision_tr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_tr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_ar',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_en',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_ru',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_tr',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='button1_text_ar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='button1_text_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='button1_text_ru',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='button1_text_tr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='button2_text_ar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='button2_text_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='button2_text_ru',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='button2_text_tr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='description_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='description_tr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='subtitle_ar',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='subtitle_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='subtitle_ru',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='subtitle_tr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='title_ar',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='title_tr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='author_ar',
            field=models.CharField(default='VAAM Team', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='author_en',
            field=models.CharField(default='VAAM Team', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='author_ru',
            field=models.CharField(default='VAAM Team', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='author_tr',
            field=models.CharField(default='VAAM Team', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='content_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='content_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='content_tr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='meta_description_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='meta_description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='meta_description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='meta_description_tr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='meta_title_ar',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='meta_title_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='meta_title_ru',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='meta_title_tr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='summary_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='summary_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='summary_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='summary_tr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ar',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ru',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_tr',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='name_ar',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='name_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='name_tr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='processstep',
            name='description_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processstep',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processstep',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processstep',
            name='description_tr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processstep',
            name='title_ar',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='processstep',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='processstep',
            name='title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='processstep',
            name='title_tr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_tr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description_tr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_title_ar',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_title_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_title_ru',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_title_tr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ar',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ru',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_tr',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description_tr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='description_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='description_tr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='name_ar',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='name_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='name_tr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='productimage',
            name='alt_text_ar',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='productimage',
            name='alt_text_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='productimage',
            name='alt_text_ru',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='productimage',
            name='alt_text_tr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='productspecification',
            name='key_ar',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='productspecification',
            name='key_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='productspecification',
            name='key_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='productspecification',
            name='key_tr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='productspecification',
            name='value_ar',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='productspecification',
            name='value_en',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='productspecification',
            name='value_ru',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='productspecification',
            name='value_tr',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='client_ar',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='client_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='client_ru',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='client_tr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description_tr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='location_ar',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='location_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='location_ru',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='location_tr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='short_description_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='short_description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='short_description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='short_description_tr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title_ar',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title_ru',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title_tr',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='projectcategory',
            name='name_ar',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='projectcategory',
            name='name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='projectcategory',
            name='name_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='projectcategory',
            name='name_tr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='description_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='description_tr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='features_ar',
            field=models.TextField(blank=True, help_text='One feature per line', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='features_en',
            field=models.TextField(blank=True, help_text='One feature per line', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='features_ru',
            field=models.TextField(blank=True, help_text='One feature per line', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='features_tr',
            field=models.TextField(blank=True, help_text='One feature per line', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='short_description_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='short_description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='short_description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='short_description_tr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='title_ar',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='title_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='title_ru',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='title_tr',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='name_ar',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='name_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='name_tr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address2_ar',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address2_en',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address2_ru',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address2_tr',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address_ar',
            field=models.CharField(default='Baku, Azerbaijan', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address_en',
            field=models.CharField(default='Baku, Azerbaijan', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address_ru',
            field=models.CharField(default='Baku, Azerbaijan', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address_tr',
            field=models.CharField(default='Baku, Azerbaijan', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_description_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_description_tr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_keywords_ar',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_keywords_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_keywords_ru',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_keywords_tr',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_title_ar',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_title_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_title_ru',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_title_tr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_description_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_description_tr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_name_ar',
            field=models.CharField(default='VAAM Import and Export Trading', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_name_en',
            field=models.CharField(default='VAAM Import and Export Trading', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_name_ru',
            field=models.CharField(default='VAAM Import and Export Trading', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_name_tr',
            field=models.CharField(default='VAAM Import and Export Trading', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='working_hours_ar',
            field=models.CharField(default='Mon-Fri 9:00-18:00', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='working_hours_en',
            field=models.CharField(default='Mon-Fri 9:00-18:00', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='working_hours_ru',
            field=models.CharField(default='Mon-Fri 9:00-18:00', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='working_hours_tr',
            field=models.CharField(default='Mon-Fri 9:00-18:00', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='statistic',
            name='title_ar',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='statistic',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='statistic',
            name='title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='statistic',
            name='title_tr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='bio_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='bio_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='bio_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='bio_tr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='name_ar',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='name_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='name_tr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='position_ar',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='position_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='position_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='position_tr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='company_ar',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='company_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='company_ru',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='company_tr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='content_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='content_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='content_tr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='name_ar',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='name_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='name_tr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='position_ar',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='position_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='position_ru',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='position_tr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
