# Generated by Django 6.0.2 on 2026-02-08 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_brand_name_ar_brand_name_en_brand_name_ru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200, null=True)),
                ('title_ru', models.CharField(max_length=200, null=True)),
                ('title_tr', models.CharField(max_length=200, null=True)),
                ('title_ar', models.CharField(max_length=200, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('location', models.CharField(choices=[('main', 'Main Navigation'), ('footer', 'Footer'), ('topbar', 'Top Bar'), ('custom', 'Custom')], default='main', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('title_en', models.CharField(max_length=300, null=True)),
                ('title_ru', models.CharField(max_length=300, null=True)),
                ('title_tr', models.CharField(max_length=300, null=True)),
                ('title_ar', models.CharField(max_length=300, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('content', models.TextField(blank=True, help_text='Page HTML content')),
                ('content_en', models.TextField(blank=True, help_text='Page HTML content', null=True)),
                ('content_ru', models.TextField(blank=True, help_text='Page HTML content', null=True)),
                ('content_tr', models.TextField(blank=True, help_text='Page HTML content', null=True)),
                ('content_ar', models.TextField(blank=True, help_text='Page HTML content', null=True)),
                ('excerpt', models.TextField(blank=True, help_text='Short summary')),
                ('excerpt_en', models.TextField(blank=True, help_text='Short summary', null=True)),
                ('excerpt_ru', models.TextField(blank=True, help_text='Short summary', null=True)),
                ('excerpt_tr', models.TextField(blank=True, help_text='Short summary', null=True)),
                ('excerpt_ar', models.TextField(blank=True, help_text='Short summary', null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='pages/')),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_title_en', models.CharField(blank=True, max_length=200, null=True)),
                ('meta_title_ru', models.CharField(blank=True, max_length=200, null=True)),
                ('meta_title_tr', models.CharField(blank=True, max_length=200, null=True)),
                ('meta_title_ar', models.CharField(blank=True, max_length=200, null=True)),
                ('meta_description', models.TextField(blank=True)),
                ('meta_description_en', models.TextField(blank=True, null=True)),
                ('meta_description_ru', models.TextField(blank=True, null=True)),
                ('meta_description_tr', models.TextField(blank=True, null=True)),
                ('meta_description_ar', models.TextField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('show_in_footer', models.BooleanField(default=False, help_text='Show link in footer')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200, null=True)),
                ('title_ru', models.CharField(max_length=200, null=True)),
                ('title_tr', models.CharField(max_length=200, null=True)),
                ('title_ar', models.CharField(max_length=200, null=True)),
                ('link_type', models.CharField(choices=[('url', 'Custom URL'), ('page', 'Page'), ('home', 'Home'), ('about', 'About'), ('services', 'Services'), ('products', 'Products'), ('projects', 'Projects'), ('news', 'News'), ('contact', 'Contact')], default='url', max_length=20)),
                ('url', models.CharField(blank=True, help_text='Used when link type is "Custom URL"', max_length=500)),
                ('icon', models.CharField(blank=True, help_text='CSS icon class e.g. fas fa-home', max_length=100)),
                ('target', models.CharField(choices=[('_self', 'Same Window'), ('_blank', 'New Window')], default='_self', max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('css_class', models.CharField(blank=True, help_text='Extra CSS classes', max_length=200)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.menu')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.menuitem')),
                ('page', models.ForeignKey(blank=True, help_text='Used when link type is "Page"', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.page')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
