# Generated by Django 6.0.2 on 2026-02-08 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_news_is_published_alter_news_published_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='logo_admin',
            field=models.ImageField(blank=True, help_text='Logo for admin panel sidebar and login page', null=True, upload_to='site/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo_white',
            field=models.ImageField(blank=True, help_text='White/light logo for dark backgrounds (footer etc.)', null=True, upload_to='site/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Browser tab icon (recommended: 32x32 or 64x64 PNG)', null=True, upload_to='site/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, help_text='Main logo for header and light backgrounds', null=True, upload_to='site/'),
        ),
    ]
