# Generated by Django 6.0.2 on 2026-02-19 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sitesettings_logo_admin_sitesettings_logo_white_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_en', models.CharField(max_length=200, null=True)),
                ('name_ru', models.CharField(max_length=200, null=True)),
                ('name_tr', models.CharField(max_length=200, null=True)),
                ('name_ar', models.CharField(max_length=200, null=True)),
                ('code', models.CharField(blank=True, help_text='ISO country code e.g. AZ, TR, RU', max_length=10)),
                ('flag_icon', models.CharField(blank=True, help_text='Flag emoji or CSS class', max_length=100)),
                ('image', models.ImageField(blank=True, help_text='Country flag or representative image', null=True, upload_to='countries/')),
                ('description', models.TextField(blank=True, help_text='Short note about operations in this country')),
                ('description_en', models.TextField(blank=True, help_text='Short note about operations in this country', null=True)),
                ('description_ru', models.TextField(blank=True, help_text='Short note about operations in this country', null=True)),
                ('description_tr', models.TextField(blank=True, help_text='Short note about operations in this country', null=True)),
                ('description_ar', models.TextField(blank=True, help_text='Short note about operations in this country', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('delivery_country', models.CharField(help_text='Country where product will be delivered', max_length=200)),
                ('product_description', models.TextField(help_text='Detailed description of the product(s) needed')),
                ('quantity', models.CharField(blank=True, help_text='Estimated quantity needed', max_length=200)),
                ('budget_range', models.CharField(blank=True, help_text='Approximate budget range', max_length=200)),
                ('additional_notes', models.TextField(blank=True, help_text='Any additional requirements or notes')),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewing', 'Reviewing'), ('quoted', 'Quoted'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='new', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_category', models.ForeignKey(blank=True, help_text='Product category of interest', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='core.productcategory')),
            ],
            options={
                'verbose_name_plural': 'Product Inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
